eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#for actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
#      base-path: "/hotelservice"
  endpoint:
    health:
      show-details: "ALWAYS"
